--region *.lua
--Date 2017-4-4
--Author zhangenzhi
--此文件由[BabeLua]插件自动生成


local LordSceneRes = 
{
    paths   =
    {
        "game/lord/effect/doudizhu4_beijing/doudizhu4_beijing.ExportJson",
        "game/lord/effect/doudizhu4_chuntian/doudizhu4_chuntian.ExportJson",
        "game/lord/effect/doudizhu4_dengdai/doudizhu4_dengdai.ExportJson",
        "game/lord/effect/doudizhu4_dizhumao/doudizhu4_dizhumao.ExportJson",
        "game/lord/effect/doudizhu4_feiji/doudizhu4_feiji.ExportJson",
        "game/lord/effect/doudizhu4_huojian/doudizhu4_huojian.ExportJson",
        "game/lord/effect/doudizhu4_jiesuan/doudizhu4_jiesuan.ExportJson",
        "game/lord/effect/doudizhu4_jingdeng/doudizhu4_jingdeng.ExportJson",
        "game/lord/effect/doudizhu4_liandui/doudizhu4_liandui.ExportJson",
        "game/lord/effect/doudizhu4_shunzi/doudizhu4_shunzi.ExportJson",
        "game/lord/effect/doudizhu4_tishi/doudizhu4_tishi.ExportJson",
        "game/lord/effect/doudizhu4_zhadan/doudizhu4_zhadan.ExportJson",
        "game/lord/effect/jueseqiehuan_1/jueseqiehuan_1.ExportJson",
     },
}

LordSceneRes.vecReleaseAnim = LordSceneRes.paths
LordSceneRes.vecReleasePlist = 
{
    {"game/lord/gui/gui-lord-poker.plist","game/lord/gui/gui-lord-poker.png"},
    {"game/lord/gui/gui-lord.plist", "game/lord/gui/gui-lord.png", },
    {"hall/plist/gui-vip.plist",     "hall/plist/gui-vip.png",   },--头像框用到
}
LordSceneRes.vecReleaseImg = {}
LordSceneRes.vecReleaseSound = 
{
    "game/lord/sound/audio_reminded.mp3",
    "game/lord/sound/Man_1.mp3",
    "game/lord/sound/Man_10.mp3",
    "game/lord/sound/Man_11.mp3",
    "game/lord/sound/Man_12.mp3",
    "game/lord/sound/Man_13.mp3",
    "game/lord/sound/Man_14.mp3",
    "game/lord/sound/Man_15.mp3",
    "game/lord/sound/Man_2.mp3",
    "game/lord/sound/Man_3.mp3",
    "game/lord/sound/Man_4.mp3",
    "game/lord/sound/Man_5.mp3",
    "game/lord/sound/Man_6.mp3",
    "game/lord/sound/Man_7.mp3",
    "game/lord/sound/Man_8.mp3",
    "game/lord/sound/Man_9.mp3",
    "game/lord/sound/Man_baojing1.mp3",
    "game/lord/sound/Man_baojing2.mp3",
    "game/lord/sound/Man_bujiabei.mp3",
    "game/lord/sound/Man_bujiao.mp3",
    "game/lord/sound/Man_buyao1.mp3",
    "game/lord/sound/Man_buyao2.mp3",
    "game/lord/sound/Man_buyao3.mp3",
    "game/lord/sound/Man_buyao4.mp3",
    "game/lord/sound/Man_dani1.mp3",
    "game/lord/sound/Man_dani2.mp3",
    "game/lord/sound/Man_dani3.mp3",
    "game/lord/sound/Man_dui1.mp3",
    "game/lord/sound/Man_dui10.mp3",
    "game/lord/sound/Man_dui11.mp3",
    "game/lord/sound/Man_dui12.mp3",
    "game/lord/sound/Man_dui13.mp3",
    "game/lord/sound/Man_dui2.mp3",
    "game/lord/sound/Man_dui3.mp3",
    "game/lord/sound/Man_dui4.mp3",
    "game/lord/sound/Man_dui5.mp3",
    "game/lord/sound/Man_dui6.mp3",
    "game/lord/sound/Man_dui7.mp3",
    "game/lord/sound/Man_dui8.mp3",
    "game/lord/sound/Man_dui9.mp3",
    "game/lord/sound/Man_feiji.mp3",
    "game/lord/sound/Man_jiabei.mp3",
    "game/lord/sound/Man_liandui.mp3",
    "game/lord/sound/Man_sandaiyi.mp3",
    "game/lord/sound/Man_sandaiyidui.mp3",
    "game/lord/sound/Man_score1.mp3",
    "game/lord/sound/Man_score2.mp3",
    "game/lord/sound/Man_score3.mp3",
    "game/lord/sound/Man_shunzi.mp3",
    "game/lord/sound/Man_sidaier.mp3",
    "game/lord/sound/Man_sidailiangdui.mp3",
    "game/lord/sound/Man_tuple1.mp3",
    "game/lord/sound/Man_tuple10.mp3",
    "game/lord/sound/Man_tuple11.mp3",
    "game/lord/sound/Man_tuple12.mp3",
    "game/lord/sound/Man_tuple13.mp3",
    "game/lord/sound/Man_tuple2.mp3",
    "game/lord/sound/Man_tuple3.mp3",
    "game/lord/sound/Man_tuple4.mp3",
    "game/lord/sound/Man_tuple5.mp3",
    "game/lord/sound/Man_tuple6.mp3",
    "game/lord/sound/Man_tuple7.mp3",
    "game/lord/sound/Man_tuple8.mp3",
    "game/lord/sound/Man_tuple9.mp3",
    "game/lord/sound/Man_wangzha.mp3",
    "game/lord/sound/Man_zhadan.mp3",
    "game/lord/sound/MusicEx_Lose.mp3",
    "game/lord/sound/MusicEx_Win.mp3",
    "game/lord/sound/Special_alert.mp3",
    "game/lord/sound/Special_Baojingjiacheng.mp3",
    "game/lord/sound/Special_Bomb_New.mp3",
    "game/lord/sound/Special_Chuntian.mp3",
    "game/lord/sound/Special_Dispatch.mp3",
    "game/lord/sound/Special_give.mp3",
    "game/lord/sound/Special_Long_Bomb.mp3",
    "game/lord/sound/Special_plane.mp3",
    "game/lord/sound/Special_querendizhu.mp3",
    "game/lord/sound/Special_star.mp3",
    "game/lord/sound/SpecSelectCard.mp3",
    "game/lord/sound/Woman_1.mp3",
    "game/lord/sound/Woman_10.mp3",
    "game/lord/sound/Woman_11.mp3",
    "game/lord/sound/Woman_12.mp3",
    "game/lord/sound/Woman_13.mp3",
    "game/lord/sound/Woman_14.mp3",
    "game/lord/sound/Woman_15.mp3",
    "game/lord/sound/Woman_2.mp3",
    "game/lord/sound/Woman_3.mp3",
    "game/lord/sound/Woman_4.mp3",
    "game/lord/sound/Woman_5.mp3",
    "game/lord/sound/Woman_6.mp3",
    "game/lord/sound/Woman_7.mp3",
    "game/lord/sound/Woman_8.mp3",
    "game/lord/sound/Woman_9.mp3",
    "game/lord/sound/Woman_baojing1.mp3",
    "game/lord/sound/Woman_baojing2.mp3",
    "game/lord/sound/Woman_bujiabei.mp3",
    "game/lord/sound/Woman_bujiao.mp3",
    "game/lord/sound/Woman_buyao1.mp3",
    "game/lord/sound/Woman_buyao2.mp3",
    "game/lord/sound/Woman_buyao3.mp3",
    "game/lord/sound/Woman_buyao4.mp3",
    "game/lord/sound/Woman_dani1.mp3",
    "game/lord/sound/Woman_dani2.mp3",
    "game/lord/sound/Woman_dani3.mp3",
    "game/lord/sound/Woman_dui1.mp3",
    "game/lord/sound/Woman_dui10.mp3",
    "game/lord/sound/Woman_dui11.mp3",
    "game/lord/sound/Woman_dui12.mp3",
    "game/lord/sound/Woman_dui13.mp3",
    "game/lord/sound/Woman_dui2.mp3",
    "game/lord/sound/Woman_dui3.mp3",
    "game/lord/sound/Woman_dui4.mp3",
    "game/lord/sound/Woman_dui5.mp3",
    "game/lord/sound/Woman_dui6.mp3",
    "game/lord/sound/Woman_dui7.mp3",
    "game/lord/sound/Woman_dui8.mp3",
    "game/lord/sound/Woman_dui9.mp3",
    "game/lord/sound/Woman_feiji.mp3",
    "game/lord/sound/Woman_jiabei.mp3",
    "game/lord/sound/Woman_liandui.mp3",
    "game/lord/sound/Woman_sandaiyi.mp3",
    "game/lord/sound/Woman_sandaiyidui.mp3",
    "game/lord/sound/Woman_score1.mp3",
    "game/lord/sound/Woman_score2.mp3",
    "game/lord/sound/Woman_score3.mp3",
    "game/lord/sound/Woman_shunzi.mp3",
    "game/lord/sound/Woman_sidaier.mp3",
    "game/lord/sound/Woman_sidailiangdui.mp3",
    "game/lord/sound/Woman_tuple1.mp3",
    "game/lord/sound/Woman_tuple10.mp3",
    "game/lord/sound/Woman_tuple11.mp3",
    "game/lord/sound/Woman_tuple12.mp3",
    "game/lord/sound/Woman_tuple13.mp3",
    "game/lord/sound/Woman_tuple2.mp3",
    "game/lord/sound/Woman_tuple3.mp3",
    "game/lord/sound/Woman_tuple4.mp3",
    "game/lord/sound/Woman_tuple5.mp3",
    "game/lord/sound/Woman_tuple6.mp3",
    "game/lord/sound/Woman_tuple7.mp3",
    "game/lord/sound/Woman_tuple8.mp3",
    "game/lord/sound/Woman_tuple9.mp3",
    "game/lord/sound/Woman_wangzha.mp3",
    "game/lord/sound/Woman_zhadan.mp3",
}

LordSceneRes.vecReleaseMusic = {
    "game/lord/sound/MusicEx_Exciting.mp3",
    "game/lord/sound/MusicEx_Normal.mp3",
    "game/lord/sound/MusicEx_Normal2.mp3",
    "game/lord/sound/MusicEx_Welcome.mp3",
}


LordSceneRes.vecRLoadingPlist = LordSceneRes.vecReleasePlist
LordSceneRes.vecRLoadingImg = LordSceneRes.vecReleaseImg
LordSceneRes.vecLoadingAnim = LordSceneRes.vecReleaseAnim
LordSceneRes.vecLoadingSound = {}
LordSceneRes.vecLoadingMusic = LordSceneRes.vecReleaseMusic

return LordSceneRes

--endregion