---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mg.
--- DateTime: 2019/3/20 16:26
---

local Brnn_Res = {}

Brnn_Res.ANI_OF_CHANGEUSER = {
    FILEPATH = "game/handredcattle/effect/longyuhufanpai_Animation/longyuhufanpai_Animation.ExportJson",
    FILENAME = "longyuhufanpai_Animation",
    ANILIST = {
        BEGIN = {
            NAME = "Animation1",
            NODES = {
                HEAD = "Layer6_Copy1",  --动画节点，用于替换资源
            },
        },
        END = {
            NAME = "Animation2",
            NODES = {
                HEAD = "Layer6_Copy1",  --动画节点，用于替换资源
            },
        },
    },
}
Brnn_Res.PNG_OF_HEAD = "gui-icon-head-%02d.png" -- 头像
return Brnn_Res