---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mg.
--- DateTime: 2019/3/22 11:11
---

------local JettonLayer = class("JettonLayer",cc.Layer)

local JettonItem = class("JettonItem")

function JettonItem:ctor(Viewnode, parentNode, index)

    self.m_viewNode = Viewnode
    self.m_index = index
    self.m_Button = parentNode         --筹码按钮
    self.m_Image = self.m_Button:getChildByName("Image_jetton_ani_"..index) --筹码动画

    -- 选中
    self.m_Image:runAction(cc.RepeatForever:create(cc.RotateBy:create(1.5, 360)))
    self.m_Image:setVisible(false)

    self.m_BtnMark = self.m_Button:getChildByName("Button_jetton_mark_"..index)

    -- 绑定事件
    self.m_Button:addClickEventListener(handler(self, self.onClick))
end

-- 点击时调用
function JettonItem:onClick()
    print('ChipBtnClass click', self._chipVal)

    -- 切换选中效果
    if not self.m_BtnMark:isVisible() then
        self:setSel(true)
    end

    self.m_viewNode:onBetNumClicked(self.m_index)
end

function JettonItem:setSel(b)
    self.m_Image:setVisible(b)
end

function JettonItem:setEnabled(enabled)
    self.m_BtnMark:setVisible(not enabled)
end

return JettonItem